name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Create .env file
        run: |
          echo "NODE_ENV=test" > .env

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: Install docker compose
        run: sudo apt-get update && sudo apt-get install docker-compose

      - name: Run Tests
        run: pnpm test

      - name: Teardown
        run: pnpm dev:teardown
